### ISSUE TITLE
LLVM build fails with "libtool: unrecognized option `-static'"

### ISSUE THREAD

**Issue by prokash** [avast-tl/retdec#118]
I downloaded the source on 1/26/2018. It does have lot more help. But I'm having problem with the LLVM part of the whole build ---
```
[  1%] Performing build step for 'llvm-project'
[  0%] Linking CXX static library ../libLLVMSupport.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make[5]: *** [lib/libLLVMSupport.a] Error 1
make[4]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [external/src/llvm-project-stamp/llvm-project-build] Error 2
make[1]: *** [deps/llvm/CMakeFiles/llvm-project.dir/all] Error 2
```
Now if I go directly to the source of this external component and issue a make, I get --
```
[  0%] Linking CXX static library ../libLLVMSupport.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make[2]: *** [lib/libLLVMSupport.a] Error 1
make[1]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/all] Error 2
make: *** [all] Error 2
```
So is anyone else seeing this on OS X 10.11 build environment ???

Thanks in advance,
Prokash

**Comment by PeterMatula** [comment]
What does command `which libtool` return?

**Comment by prokash** [comment]
Thanks for change of Title! 
I guess that also answers PeterMatula's Question ...

**Comment by s3rvac** [comment]
@prokash I suspect that you have an incompatible version of `libtool` in your `PATH` (e.g. GNU libtool from MacPorts or Homebrew). You will need to adjust your `PATH` so that `libtool` runs `/usr/bin/libtool` that comes from Xcode (running `which libtool` should print `/usr/bin/libtool`). For more details, see the following links
* https://coderwall.com/p/nmgkyw/libv8-install-fails-with-libtool-unrecognized-option-static-error
* https://github.com/nodejs/node/issues/2341#issuecomment-129387803
* https://stackoverflow.com/questions/38301930/libtool-unrecognized-option-static/38552393
* http://flummox-engineering.blogspot.com/2014/04/libtool-unrecognized-option-static.html

Let us know if this solved the build issue.

**Comment by s3rvac** [comment]
I am closing the issue as there was no reaction in the past 14 days. If the hint above did not fix the build issue for you, feel free to reopen.
