### ISSUE TITLE
bin2pat: incorrect handling of x86_64 relocations

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec#127]
Relocations are incorrectly masked.

**Output:**
```
rule file_0_1 {
    ...
    strings:
        $1 = { FF 25 0E 00 00 00 }
    condition:
        $1
}
```

**Expected output:**
```
rule file_0_1 {
    ...
        refs = "0002 symbol_name" 
    strings:
        $1 = { FF 25 ?? ?? ?? ?? }
    condition:
        $1
}
```

**Comment by mbandzi** [comment]
Fixed in [1ac2dca79](https://github.com/avast-tl/retdec/commit/1ac2dca79e735f7a491e14624665e75d4b2aa7ef).

Also support for fat Mach-O binaries was turned off in bin2pat in [bc53974](https://github.com/avast-tl/retdec/commit/bc53974d2f777aefb3ab87bc902b561f8273939d). This would be relatively hard to fix due to fat binary offsets problem - it is better to just print error message and tell user to use `retdec-macho-extractor`. There are only few use cases where this could be useful.
