### ISSUE TITLE
Installation: binaries and wrapper scripts?

### ISSUE THREAD

**Issue by dtzWill** [avast-tl/retdec#163]
Could/should wrapped binaries be put into somewhere like "libexec"?

Currently installation ends up having, for example, both retdec-decompile.sh and retdec-decompile in "bin", making tab-completion annoying (first suggestion is wrong one)? Is that an oversight or is this intentional/necessary?

Also if binaries are put elsewhere, scripts wouldn't need to have the ".sh" extension which is a bit nicer IMHO.

**Comment by PeterMatula** [comment]
It is not necessary.
It is not exactly intentional, it just kind of happened this way.
We could do something like you suggested to make it slightly better, but I don't think we will. It would take some time, make the whole installation process more complicated (Linux/Windows/macOS), and would not help with the basic problem - that there are such pairs in the first place. I would rather use the time to improve either decompilation quality, or make the whole framework less intricate. For example, we would like to get rid of these wrappers when possible. If there is some bash code left, we would like to rewrite it to Python, etc.
