### ISSUE TITLE
`bash decompile.sh` fails with errors when run on Windows 10 with Windows Subsystem for Linux

### ISSUE THREAD

**Issue by ACB1337** [avast-tl/retdec#18]
Running: bash decompile.sh test.exe results in multiple errors.
Running: decompile.sh test.exe from the command line works just fine.

**Comment by s3rvac** [comment]
Thank you for the report. What Windows version do you use? From which environment/console did you run `bash decompile.sh test.exe`? What errors did you get?

I tried to run `bash decompile.sh test.exe` from the following environments and in every case, the command worked as expected:
* MSYS2 shell via `C:\msys64\msys2_shell.cmd`
* ConEmu shell via `C:\msys64\usr\bin\bash.exe -i`
* `cmd.exe`

On the contrary, `decompile.sh test.exe` failed in all the above environments. I got either the expected error `bash: decompile.sh: command not found` or `Windows can't open this type of file (.sh)` in `cmd.exe`.

**Comment by ACB1337** [comment]
Im on windows 10 newest update and I ran the commands from cmd.exe.

This is the output if I prefix the command with 'bash'
```
E:\retdec\bin>bash decompile.sh update-server.exe
##### Checking if file is a Mach-O Universal static library...
RUN: /mnt/e/retdec/bin/macho-extractor --list /mnt/e/retdec/bin/update-server.exe

##### Checking if file is an archive...
RUN: /mnt/e/retdec/bin/ar-extractor --arch-magic /mnt/e/retdec/bin/update-server.exe
/mnt/e/retdec/bin/utils.sh: line 55: /mnt/e/retdec/bin/ar-extractor: No such file or directory
Not an archive, going to the next step.

##### Gathering file information...
RUN: /mnt/e/retdec/bin/fileinfo -c /mnt/e/retdec/bin/update-server.c.json --similarity /mnt/e/retdec/bin/update-server.exe --no-hashes=all --crypto /mnt/e/retdec/bin/../share/generic/yara_patterns/signsrch/signsrch.yara
decompile.sh: line 667: /mnt/e/retdec/bin/fileinfo: No such file or directory
```

Without bash everything works as expected.

**Comment by s3rvac** [comment]
Do you use Bash from the [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), [MSYS2](http://www.msys2.org/), [Cygwin](https://www.cygwin.com/), or even from something else?

**Comment by ACB1337** [comment]
Nope just regular plain old command prompt. Though I do have WSL installed dont know if that might interfere.

**Comment by s3rvac** [comment]
Well, to run `decompile.sh`, you need to have Bash on your system. I believe that the problem might be caused by Bash from WSL as we have AFAIK never tried to run RetDec via WSL :-).

I will have to ask someone with Windows 10 + WSL to verify and debug this as I currently do not have access to any Windows 10 machine.

**Comment by s3rvac** [comment]
We have found out that the problem is indeed caused by the use of Bash from WSL instead of Bash from MSYS2.

@ACB1337, could you please try running `C:\msys64\usr\bin\bash.exe decompile.sh test.exe` (or wherever you have installed MSYS2) instead of `bash.exe decompile.sh test.exe`? If this works, then it means that Bash from WSL is in your `PATH` before Bash from MSYS2, and thus when you run `bash.exe decompile.sh test.exe`, the system picks up the "wrong" Bash (from WSL).

**Comment by ACB1337** [comment]
Calling the correct bash.exe directly also does not work.
```
E:\retdec\bin>C:\msys64\usr\bin\bash.exe decompile.sh update-server.exe
decompile.sh: line 6: dirname: command not found
/e/retdec/bin/utils.sh: line 6: dirname: command not found
/e/retdec/bin/config.sh: line 6: dirname: command not found
/e/retdec/bin/config.sh: line 17: uname: command not found
/e/retdec/bin/config.sh: line 19: uname: command not found
/e/retdec/bin/config.sh: line 19: uname: command not found
Error: Unknown OS
```

However calling ```C:\msys64\msys2_shell.cmd -msys``` and then running the command with either bash or without does work

**Comment by jakubkroustek** [comment]
@ACB1337 Could you send us the value of your `PATH` variable? Is `c:\msys64\usr\bin\` accessible from there as mentioned in the [guide](https://github.com/avast-tl/retdec/wiki/Windows-Environment#msys2-installation-and-configuration)? And it should be listed before any WSL paths...

**Comment by ACB1337** [comment]
Ok moving the msys64 path to the very beginning has fixed the problem. Thanks. Also I had it removed some time during testing so that is where the other errors when calling the bash.exe directly have come from.

**Comment by s3rvac** [comment]
Great! Thanks for your assistance during debugging. We have added a note into the [wiki](https://github.com/avast-tl/retdec/wiki/Windows-Environment) concerning the importance of a correct `PATH` when running on Windows 10 with WSL.

**Comment by AntonKukoba1** [comment]
Well, I was able to run it under WSL. It only takes to 

1. add /mnt/<yourpath>/retdec/bin to the PATH
2. create symbolic links to all exe files in bin directory. 
3. fix file path in SH files to use just file name i.e. IN=$(basename "$IN"), OUT=$(basename "$OUT"), CONFIG=$(basename "$CONFIG") etc.
4. hard code FILECLASS="32" instead of "$CONFIG" --read --file-class (it never worked for me)

**Comment by s3rvac** [comment]
@AntonKukoba1 Thank you for the tip. For running RetDec under WSL on Windows 10, I have created a separate ticket (#85), and added a link to your tip in there.
