### ISSUE TITLE
Add an Appveyor and Travis.CI builds

### ISSUE THREAD

**Issue by Maijin** [avast-tl/retdec#2]
To automatically test every commit and pull-request and also create ready-to-use release

**Comment by Manouchehri** [comment]
For ready-to-use Linux builds, I already have a Dockerfile written. Just waiting for it to finish rebuilding so I can test it properly.

![image](https://user-images.githubusercontent.com/7232674/33908027-15b2be38-df55-11e7-847a-44bf27082f67.png)

**Comment by Manouchehri** [comment]
@Maijin Hmm, the build times out on Docker Hub. Guessing we're going to have the same problem on AppVeyor and Travis CI?

https://hub.docker.com/r/thawsystems/retdec/builds/b9tti2q2xascemdzhqcasfh/

**Comment by Maijin** [comment]
What about make -jXX ?

**Comment by Symbian9** [comment]
Setup Travis-CI for producing AppImage package!

- https://github.com/avast-tl/retdec/issues/42

**Comment by PeterMatula** [comment]
Travis: https://travis-ci.org/avast-tl/retdec
Appveyor: https://ci.appveyor.com/project/avast-tl/retdec

Notes:
- We had to significantly reduce LLVM that we use in order to pass CI time limits. Only modules that we actually need are built. This speeds up all the builds, but may be a problem in the future - migrating to new LLVM versions, using RetDec and LLVM in other ways, etc. We will see and solve the problems if/when they occur.
- Because of time limits, we use `Release` configuration with disabled optimizations - fastest combination. This is not ideal, since it is not the configuration that is used during the development nor in releases, but since we are out of the ideas to speed up the build, it has to be this way.
- Clean, full builds (without caching, see below) should regularly be in time limits on all 3 systems - Linux, MacOS, Windows.
- We do not use any kind of caching on Windows. Build takes around 40 to 50 min. Because of this, we test only one configuration at the moment.
- We use `ccache` on Linux and MacOS. `ccache` slows down the build. MacOS should still be fine, but clean, full build on Linux with `ccache` enabled does not end in time limit. Subsequent builds should. We decided to use `ccache` for now, and if some build fails because of the time limit, to manually restart it. We hope it will not happen often. If it will, we may disable caching altogether.
- MacOS builds in Travis start really slow - huge job backlog.
- There might be more enhancements in the future - more build configurations, better caching([mtime_cache](https://github.com/iboB/mtime_cache)?), different/faster CI for MacOS, etc. But for now, we consider this solved. We will use it for some time and see how well it works and what improvements are needed.
- Any developer needs to run his/her own regression tests. We will not accept any pull request that breaks any regression test on any system. It would be the best, if this was automated as well, but there is no way that this could run on public/free infrastructure. It is simply to resource-consuming.

**Comment by Karaulov** [comment]
how to download nightbuilds from appveyor ?

**Comment by silverbacknet** [comment]
If they were public, they'd show up as artifacts, but they don't seem to be.

**Comment by Karaulov** [comment]
RetDec opensource and uses appveyor for build ? Why can't download artifacts ?(night build)
