### ISSUE TITLE
retdec.com not works

### ISSUE THREAD

**Issue by Karaulov** [avast-tl/retdec#236]
![uanbibg 1](https://user-images.githubusercontent.com/6445336/36963498-90de2d36-2064-11e8-997b-b726ca3cc270.png)

I tried many files who i need check, but all failed with memory limit.

**Comment by Karaulov** [comment]
I tried macos, .dll .exe files, all crashes with error "memory limit".

**Comment by Karaulov** [comment]
Now i upload simple .dll 300kb size. I wait more than 10 minutes. Nothing, stopped at "Data-flow analysis..." phase.

**Comment by Karaulov** [comment]
another small dll file: (150kb)

![kbsdfms 1](https://user-images.githubusercontent.com/6445336/36967364-90e63128-2070-11e8-90a0-9385ef104a22.png)

**Comment by s3rvac** [comment]
We would like to kindly ask you to stop spamming our issue tracker. From the information that you provided, there is no way to diagnose what is wrong. You did not even attach the input files or told us what settings did you use.

We are aware that decompilations sometime take too much memory. For more details, see e.g. #13 and #16.

There are better ways of helping us than mindless bashing. For instance, well-crafted, non-duplicate bug reports are welcome.

**Comment by Karaulov** [comment]
retdec.com no have log files ? You can't just open debug console or download input files to check ?

**Comment by silverbacknet** [comment]
@Karaulov It's worth remembering that the service level on a free online demonstration of the technology isn't anything like a paid service, and priority is going to be given to already-triaged problems over unknown demonstrations of the same error. The memory limit problem is actively being worked on, but it's a hard problem with many design tradeoffs to make; it'll be fixed when it's fixed, and the fixes will come to the web interface at the same time. Asking the developers to spend time hunting down your inputs instead of providing them isn't effective either.

@s3rvac Maybe it'd be a good idea to show the current server load, and a disclaimer that the decompilation may not complete due to system limits?
