### ISSUE TITLE
 Detected a possible infinite recursion (goto support failed); quitting...

### ISSUE THREAD

**Issue by DennisD2** [avast-tl/retdec#276]
Hello,
when decompiling a large function that checks many things, I get this error.
Is the decompilation result in this case incomplete? can I prevent quitting somehow?
Function is here https://github.com/DennisD2/tomorrow/blob/master/src/morrow/sa.c, function InitGuiSweep().

**Comment by DennisD2** [comment]
And the library binary here: https://github.com/DennisD2/tomorrow/blob/master/src/morrow/orig/lib/Mtcpnp32.dll

**Comment by s3rvac** [comment]
Hi. This message is emitted into the generated C code when the structuring algorithm in `llvmir2hll` fails to properly structure the code. This will have to be fixed by improving the code-structuring algorithm in `bin2llvmir`. I am marking this as a bug.

**Comment by silverbacknet** [comment]
Another file that exhibits this infinite recursion behavior, if you need another test-case.
[SmoothUV.zip](https://github.com/avast-tl/retdec/files/2125955/SmoothUV.zip)

**Comment by madscientist159** [comment]
Can this be worked around using IDA?  Just hit it on a relatively small static library.

**Comment by PeterMatula** [comment]
After the `new` LLVM IR to BIR converter became the default converter (#211), this should happen a lot less. Well, in fact it cannot happen at all, since the `Detected a possible infinite recursion (goto support failed); quitting...` error is present only in the old converter. But that does not mean that code structuring is always good, or at least better than before. It should, however, be better in most cases.
