### ISSUE TITLE
Difference results between using .sh and .exe on Window 10

### ISSUE THREAD

**Issue by Joel-MalwareBenchmark** [avast-tl/retdec#280]
[using_sh.zip](https://github.com/avast-tl/retdec/files/1931756/using_sh.zip)
[using_exe.zip](https://github.com/avast-tl/retdec/files/1931760/using_exe.zip)

When I used `decompile.sh` in mingw on win10 ,I obtained the results in `using_sh.zip.`
When I used `fileinfo.exe bin2llvmir.exe  and llvmir2hll.exe`  in cmd on win10 ,I obtained the results in `using_exe.zip.`

However the results (IR .ll file ) is difference.
When I used decompile.sh , the IR (.ll) :
```
%v5_8048b59 = call i32* @memcpy(i32* nonnull %stack_var_-40, i32* bitcast ([32 x i8]* @global_var_8048cf4.21 to i32*), i32 24)
declare i32* @memcpy(i32*, i32*, i32) local_unnamed_addr
```
However,when I used the fileinfo.exe, bin2llvmir.exe,llvm2hill.exe, the IR(.ll):
```
%v0_80484f0 = call i32 @memcpy()
declare i32 @memcpy() local_unnamed_addr
```
The memcpy() couldn't recognize correctly in it. And the params could not added.
The command when I used `fileinfo.exe bin2llvmir.exe  and llvmir2hll.exe` is the same as `decompile.sh`

The command I used could be review in [a.zip](https://github.com/avast-tl/retdec/files/1931817/a.zip)

**Comment by s3rvac** [comment]
Hi. The problem is that your Python script does not do the same thing as `decompile.sh`. In `decompile.sh`, we run not only `fileinfo.exe`, `bin2llvmir.exe` and `llvmir2hll`, but also `retdec-config.exe`, `unpack.sh`, and other programs/scripts. You would need a complete rewrite of `decompile.sh` to match its behavior. The fact that you get different outputs is most probably because your Python script does not run `retdec-config.exe` to include paths to type-information files and statically linked code signatures.

So, please use `decompile.sh` and not a custom script. Otherwise, you are on your own and we will not be able to help you. Be sure that you are using `decompile.sh` before opening another issue.
