### ISSUE TITLE
Pre-built package doesn't include the file 'retdec-decompiler.sh' or 'retdec-decompiler.exe'

### ISSUE THREAD

**Issue by ftk-sostupid** [avast-tl/retdec#306]
I download the pre-built package from the url you gave.
But my folder shows like this:
![default](https://user-images.githubusercontent.com/30171892/40416907-18ee0428-5eb1-11e8-9a60-47645b9070bb.png)
Is there some steps you haven't mentioned?
Or how can I resolve this and use it normally?

**Comment by s3rvac** [comment]
Hi. The pre-built package that you downloaded contains RetDec version 3.0. However, the guidelines in the README file are for the current development version (`master` branch), which has not yet been released. In this upcoming version, we have e.g. renamed `decompile.sh` to `retdec-decompiler.sh`, which is why you do not see that file in your directory.

So, in version 3.0, you should use `decompile.sh` instead of `retdec-decompiler.sh`. For more details, you can view [this README file](https://github.com/avast-tl/retdec/blob/c42dfb144b2de4b2769863c5cd0da6afab801e93/README.md), which is for version 3.0.
