### ISSUE TITLE
"SyntaxError: invalid syntax" when trying to run the generated Python code

### ISSUE THREAD

**Issue by jk2K** [avast-tl/retdec#327]
I decompiled the binary program using retdec, successfully got the python code, there is a piece of code like this
```
g14 = &g92
g15 = &g93
g16 = &g94
g52 = &g385
g59 = &g311
g66 = &g306
g73 = &g307
g77 = &g311
g78 = &g306
g80 = &g304
g82 = &g305
g85 = &g308
g87 = &g302
g88 = &g303
g95 = &g300A
g128 = &g301
g133 = &g389
g134 = &g388
g135 = &g386
g136 = &g390
g143 = &g387
g145 = &g312
g146 = &g391
g154 = &g392
g155 = &g310
```

I used Python3 to run the file, get below error， I don't know where the problem is，Please help me， thanks

```bash
$ python test.py
  File "test.py", line 624
    g14 = &g92
          ^
SyntaxError: invalid syntax
```

## Environment Info
- Windows 10 1803
- Python3

**Comment by s3rvac** [comment]
Hi. The code that RetDec generates when you set the target language to `py` is an artificial, Python-like language. It cannot be executed via standard Python interpreters. The reason is that the code is more like _C without explicit types_ as it borrows several constructs from the C language, such as pointers, taking the address of a variable (`&`), dereferencing a pointer (`*`), or `goto`. The generated Python-like code is only meant to be read by people, not executed.
