### ISSUE TITLE
Support other LLVM versions

### ISSUE THREAD

**Issue by rainoftime** [avast-tl/retdec#35]
Hi, 
It would be great if we could adapt retdec to support other LLVM versions. For instance,  one can then combine retdec with other LLVM based tools such as the KLEE symbolic executor. 

Is there any plan for supporting other LLVM versions? Or could you give some advice on how to do this? I noticed that retdec depends on the project https://github.com/avast-tl/capstone2llvmir. Perhaps we should start from it?

**Comment by s3rvac** [comment]
Hi, unfortunately, support for other versions of LLVM is not possible, as explained [here](https://github.com/avast-tl/retdec/issues/14#issuecomment-351469327) and [here](https://github.com/avast-tl/retdec/issues/14#issuecomment-351469590) (#14).

In short:
1. We currently need exactly LLVM 3.9.1 due to major differences between LLVM releases (API, behavior, optimizations, etc.). However, we would like to update our version of LLVM to LLVM 5.0, hopefully soon.
2. [Our version](https://github.com/avast-tl/llvm) of LLVM contains many customizations that we need for RetDec, and RetDec would not work properly with an upstream (vanilla) version without our changes.
