### ISSUE TITLE
LLVM ERROR: Could not acquire a cryptographic context: Unknown error (0x7F)

### ISSUE THREAD

**Issue by asimaranov** [avast-tl/retdec#387]
Hi! I got the following error
Running phase: Initialization ( 0.00s )
Running phase: LLVM ( 0.03s )
Running phase: Providers initialization ( 0.03s )
Running phase: Input binary to LLVM IR decoding ( 1.31s )
LLVM ERROR: Could not acquire a cryptographic context: Unknown error (0x7F)
Error: Decompilation to LLVM IR failed
Windows 7, 64b version of decompiler. What could be the problem?

**Comment by s3rvac** [comment]
Hi. I believe this is caused by insufficient memory in the system when decompiling larger files (see also #73 and #47). Questions:
1. Could you attach the input binary file that you are trying to decompile?
2. How much RAM do you have?
3. Does this happen when decompiling all files, or just with some of them?
4. You can try decompiling the file as follows, which will disable the default memory limit (half of system RAM). However, beware that the decompilation may eat all your memory:
    ```
    python retdec-decompiler.py --no-memory-limit FILE
    ```

**Comment by s3rvac** [comment]
@asimaranov Does the issue persist or were you able to resolve it? If the issue persists, please provide answers to the four questions above. If you were able to resolve it, please tell us what you have done. This may be handy for other users who stumble upon the same error in the future.

**Comment by s3rvac** [comment]
Closing for the lack of response.
