### ISSUE TITLE
retdec-llvmir2hll "No such file or directory" even though file exists

### ISSUE THREAD

**Issue by BowDown097** [avast-tl/retdec#419]
My computer crashed while running retdec due to too much memory usage, so I continued from the last step I was on, which was retdec-llvmir2hll. Although, this did not work. I set the ".c.backend.ll" file as the input file by running specifically (in the retdec directory, where the file exists):
retdec-llvmir2hll Battles-Win.c.backend.ll
And it returned "No such file or directory" even though the file exists. Is there anything extra I need to do for this to work?
![image](https://user-images.githubusercontent.com/42720004/47290534-d50c9000-d5b4-11e8-9e14-71755b4f669b.png)

**Comment by s3rvac** [comment]
Hi. The command that you are trying to run is incomplete. You have to run a complete `llvmir2hll` command; otherwise, the decompilation will not work or may give you incorrect results. You have two options:

1) (Highly recommended.) Run `python retdec-decompiler.py Battles-Win.exe`, which will perform a complete decompilation.
2) (Not recommended.) Find the exact command that you need to run from the output of the last run of `python retdec-decompiler.py Battles-Win.exe` and run that. You will need to pass at least the following arguments:
```
retdec-llvmir2hll.exe -target-hll=c -o Battles-Win.c Battles-Win.c.backend.ll
```

**Comment by BowDown097** [comment]
Oh, ok. Thanks!

**Comment by s3rvac** [comment]
As a rule of thumb, if a decompilation does not finish within e.g. 20 minutes, then it is not worth waiting for the results as the file is either too big for RetDec or there are some decoding or code-structuring issues which cause a lot of code to be generated. In such a case, you try to decompile only selected functions:
```
python retdec-decompiler.py Battles-Win.exe --select-functions=foo,bar
```
You will have to replace `foo`, `bar`, etc. with the names of functions you want to decompile. Of course, this requires you to know which functions are inside the input file. If you do not know (or there are no symbols in the input file), you can also try decompiling only certain ranges:
```
python retdec-decompiler.py Battles-Win.exe --select-ranges=0x402000-0x410000
```
Once again, you will need to replace `0x402000-0x410000` with a correct range, which assumes that you have some information about the input file (you can use e.g. `python retdec-fileinfo.py -v Battles-Win.exe` to get it).

Nevertheless, as we have provided a solution to the reported problem, I am closing the issue.
