### ISSUE TITLE
Decrease memory usage ?

### ISSUE THREAD

**Issue by Karaulov** [avast-tl/retdec#447]
Latest build, works without error, but with warnings 'out of memory'.

Possible to decrease memory usage? (Using memory compressin/SSD disk instead of RAM/etc)

I have 4GB ram Windows 10 x64, tried to decompile small binary using 'python $RETDEC_INSTALL_DIR/bin/retdec-decompiler.py test.dll' command, got 4-5 warnings about memory

if decompiler process using more 2GB memory - wrote 'out of memory' warning.

**Comment by s3rvac** [comment]
Hi. Depending on the input file, RetDec sometimes requires a lot of memory to decompile it. This is a known issue (see #13, #16, #47 and other issues linked from there) and it will take a lot of time to fix.

Because there were numerous reports of users ending with a black screen after trying to decompile some files (#36, #81), we have added memory limitation to RetDec (#270). This limits the maximal amount of memory that RetDec can use to half of system RAM. If you wish to disable this limit and allow RetDec to use all of the available RAM, run `retdec-decompiler.py` with `--no-memory-limit`. Beware of the above-mentioned black-screen issues though.

Apart from getting more RAM or waiting for the memory issues to be fixed, I am afraid that there is nothing you can do.

**Comment by Karaulov** [comment]
@s3rvac  It works! Now process use 15GB Memory (4GB RAM, and other in page file) and no error ))

**Comment by Karaulov** [comment]
@s3rvac you can help? how to got output c file more like IDA HexRays output ?

А то я получаю какой-то вырвиглазный код который по сравнению с IDA HEXRAYS просто невозможно прочитать.

**Comment by s3rvac** [comment]
The quality of the decompiled code depends on many factors, including the size of the input file, the used compiler and optimizations, obfuscations, detection of statically linked code, the complexity of control flow etc. There is no single parameter that would magically make the output more readable.

If you know the original source code (or how the decompiled code should look like), you can submit an issue describing (**in detail**) the expected output and the actual output produced by RetDec. Do not forget to include the input binary file that you are trying to decompile. Also, please take into account that generic reports like _"produced code is unreadable"_ or _"make the code look more like from Hex-Rays"_ are useless for us. If you are happy with Hex-Rays, I suggest to use it instead of RetDec.

**Comment by silverbacknet** [comment]
This has nothing to do with retdec vs HexRays quality, it's purely an instance of HexRays recognizing a specific Win32 convention and struct; Retdec has some capability, but if you need HexRays' full capability, well, pay for it. Retdec isn't trash, because it's actually an interpretation of the real assembly that goes into the code. Claiming ASM is more readable is a joke, and fastcall/cdecl/stdcall are absolutely not relevant at all to decompilation, since they're ABI not API contracts, so I think you're way overselling this skill of yours.

**Comment by Karaulov** [comment]
@silverbacknet retdec is trash :(

No, I need to look at __fastcall / __stdcall, etc. This is very important for some cases :) 

This is can't enable in command line ?

You see there are half lost function arguments, how can this be called decompilation?



retdec : `int32_t function_1500ed80(int32_t a1) `

hexrays : `HWND __fastcall sub_1500ED80(HWND a1, LONG a2, DWORD dwProcessId)`


@silverbacknet 
You definitely have no skills if you ask why to see a calling convention like fastcall / cdecl / stdcall. This is very important in reverse engineering. :)

**Comment by 0xBEEEF** [comment]
But I must also agree that RetDec unfortunately has very little ability to recognize "structures" and to use them. You can see it quite well in the examples above. In this respect even the "Snowman" decompiler is better. I think that RetDec could be a worthy replacement for IDA, but for that an extended analysis would have to be done and structures would also have to be recognized and assigned. If I only compare the results of Snowman and RetDec, then the simplified access with the -> operator makes the code more readable. Even small changes would significantly improve the result, because otherwise the result is pure pointer arithmetic, and even in old C-times this was not easy to understand.

**Comment by minexew** [comment]
@Karaulov well why don't you contribute, genius

**Comment by Karaulov** [comment]
_I can read, i can't write )))_

Looking at how this decompiler works, it cannot be make better.

**Comment by minexew** [comment]
we're truly blessed to have your expertise on board

**Comment by Karaulov** [comment]
@minexew This is clearly meaningless, there is no point in improving this decompiler.

I argue that the ASM code is read much easier than the one given by this decompiler.
