### ISSUE TITLE
FilesystemPath::isFile returning true on non existent file

### ISSUE THREAD

**Issue by astrelsky** [avast-tl/retdec#490]
I noticed that each implementation of FilesystemPath::isFile returns !isDirectory. The isDirectory functions appear to check whether the path is valid or exists and returns false if it is not. This causes instances of isFile to return true when the path may not even exist.

In the docstring it states "The path doesn't have to be loaded." Does this imply that it may not exist? If this is the case there may be instances where a non-existent file is not caught.

**Comment by metthal** [comment]
Thank you for the bug report. I see that you also fixed it yourself, so also thank you for that! Unfortunately it's in your PR about bin2pat, so I cannot merge it separately.

Just a note about your fix. I would prefer if `FilesystemPathImplWindows::isFile()` and `FilesystemPathImplUnix::isFile()` would actually check if the path is file as they should, because I think that your fix is workaround for broken `isFile()` implementation but it doesn't fix the root cause and that is how `isFile()` is implemented.

I suggest that `FilesystemPathImplWindows::isFile()` should check if `FILE_ATTRIBUTE_DIRECTORY` bit is not set and `FilesystemPathImplUnix::isFile()` should check for `S_ISREG(st.st_mode)`.
