### ISSUE TITLE
Decompilation fails with "File is not supported archive or is not readable" when decompiling a .so file

### ISSUE THREAD

**Issue by kundanSingh11** [avast-tl/retdec#537]
Error: File is not supported archive or is not readable.

getting this error when trying to decompile .so file

**Comment by silverbacknet** [comment]
Please attach the .so file you're trying to decompile, if you can, and post the command-line you're calling retdec with and the exact version of retdec.

**Comment by kundanSingh11** [comment]
This is the file that i was using 
[libBlinkID.zip](https://github.com/avast-tl/retdec/files/3042001/libBlinkID.zip)

**Comment by s3rvac** [comment]
Hi. Shared objects (`.so`) files have to be decompiled via `retdec-decompiler.py`. I think the reason why the decompilation does not work for you is that you are using `retdec-archive-decompiler.py` instead of `retdec-decompiler.py`. Is that correct? If so, you have to use `retdec-decompiler.py` because `retdec-archive-decompiler.py` is only for archives (`.a` or `.lib` files).

**Comment by kundanSingh11** [comment]
Yes, it work thanks.
