### ISSUE TITLE
Avoid creating an empty if block

### ISSUE THREAD

**Issue by rfalke** [avast-tl/retdec#83]
Version: web version at https://retdec.com/service/api
File: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/condition_structure/ia32_elf
Output:
```
// Address range: 0x8048437 - 0x8048465
int32_t test_1_blocks_1_targets_direct_variant_0(void) {
    // 0x8048437
    if (g2 == 0) {
        // 0x8048437
        // branch -> 0x8048439
    } else {
        // 0x8048457
        puts("then/else block 3");
        // branch -> 0x8048439
    }
    // 0x8048439
    puts("return block");
    return 0;
}
```

Expected:

The condition should be inverted and there should only be the then-block without else.

**Comment by s3rvac** [comment]
Thank you for the report. I confirm that the empty body of the if statement is also generated by the current `master` (8c4b23dbbf0f2baaf6f2309fc189b054f58250ea).

**Comment by PeterMatula** [comment]
Output by the current `master`, after the `new` LLVM IR to BIR convertor became the default convertor in _llvmir2hll_:
```cpp
// Address range: 0x8048437 - 0x8048466
int32_t test_1_blocks_1_targets_direct_variant_0(void) {
    // 0x8048437
    if (g4 != 0) {
        // 0x8048457
        puts("then/else block 3");
    }
    // 0x8048439
    puts("return block");
    return 0;
}
```
I can't say empty if bodies are never going to be generated, but the current output (all the functions) look quite ok at the moment - nice test binary by the way. If you come across another issue, open an issue :-)
I added regression test (https://github.com/avast-tl/retdec-regression-tests/commit/82b373552d7c37a68cd177c8811c1df479c6b7a4) for the reported problem, but unfortunately I did not came up with a way to test all the control-flow structures in all the functions. The test itself is quite ugly - hard-coded string to check for. I don't think we have a better mechanism to check for things like this, and it would be a lot of work anyway, since there is a huge number of test cases in the `subject.exe` sample.
